spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/1611a
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 10MB
server:
  port: 8081

#pagehelper閸掑棝銆夐幓鎺嶆
pagehelper:
  helperDialect: mysql
  support-methods-arguments: true
  reasonable: true
  params: count=countSql
